server:
  port: 8083

spring:
  application:
    name: mall-tiny
  profiles:
    active: dev
#  main:
#    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: timeBus
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  iosKey:
    searchLine: 'ios:searchLine'
  harmonyKey:
    searchLine: 'harmony:searchLine'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /timeBus/busRealtime
      - /timeBus/tBusLine/getBusDataByLineName/**
      - /timeBus/tBusLineHarmony/getBusDataByLineName/**

bjbus:
  token: eyJhbGciOiJIUzI1NiIsIlR5cGUiOiJKd3QiLCJ0eXAiOiJKV1QifQ.eyJwYXNzd29yZCI6IjY0ODU5MTQzNSIsInVzZXJOYW1lIjoiYmpidXMiLCJleHAiOjE3MTYwOTExOTl9.E9KyPUNhSuVd3Ow3YK2cb5DCHhdO2QueMvIf9ey5zCM